#!/usr/bin/env node
/**
 * scripts/cap-spa-fix.js
 *
 * After `next build` (static export), dynamic [id] routes only have
 * a single placeholder page at /route/0/index.html.
 *
 * For Capacitor's WebView to resolve arbitrary IDs like /product/123/,
 * we add a fallback: copy the 404.html as the dynamic route's catch-all.
 * Then configure the Android WebView to fall back to this page.
 *
 * Alternatively, this script patches the Android WebViewClient to
 * handle SPA-like routing for the known dynamic route prefixes.
 */

const fs = require('fs');
const path = require('path');

const OUT_DIR = path.join(__dirname, '..', 'out');

// The 404.html generated by Next.js is a good SPA fallback since it
// loads the same JS bundle and lets Next.js client router take over.
const fallbackSource = path.join(OUT_DIR, '404.html');

// Also patch: copy the placeholder page to serve as index.html in the
// dynamic route's root, so /product/ works too.
const DYNAMIC_ROUTES = ['product', 'order', 'shop', 'community'];

if (!fs.existsSync(fallbackSource)) {
  console.warn('⚠ out/404.html not found — SPA fallback not created.');
  process.exit(0);
}

for (const route of DYNAMIC_ROUTES) {
  const routeDir = path.join(OUT_DIR, route);
  if (!fs.existsSync(routeDir)) {
    fs.mkdirSync(routeDir, { recursive: true });
  }

  // Copy the placeholder (0/index.html) as index.html in the route root
  const placeholderHtml = path.join(routeDir, '0', 'index.html');
  const routeIndex = path.join(routeDir, 'index.html');
  if (fs.existsSync(placeholderHtml) && !fs.existsSync(routeIndex)) {
    fs.copyFileSync(placeholderHtml, routeIndex);
    console.log(`  ✓ ${route}/index.html ← placeholder`);
  }
}

console.log('✓ SPA fallback setup complete.');
